#!/usr/bin/env python3
num1 = int(input("Give me the first number : "))
num2 = int(input("GIve me the second number : "))
bux = num1 + num2
oup = num1 - num2
ann = num1 / num2 if num2 !=0 else "undefined"
oun = num1 * num2

print(f"Thank you!")
print(f"{num1} + {num2} = {bux}")
print(f"{num1} - {num2} = {oup}")
print(f"{num1} / {num2} = {ann}")
print(f"{num1} * {num2} = {oun}")
