#!/usr/bin/env python3
def check_number_type():
    number = input("Give me a number: ")

    try:
        num = float(number)

        if num.is_integer():
            print(f"This number is an integer.")
        else:
            print(f"This number is a decimal.")
    except ValueError:
        print("Invalid input. Please enter a valid number.")

if __name__ == "__main__":
    check_number_type()
