#!/usr/bin/env python3
import math

def roundup():
    number = input("Give me a number: ")

    try:
        num = float(number)
        roundednum = math.ceil(num)
        print(roundednum)
    except ValueError:
        print("Invalid input. Please enter a valid number.")

if __name__ == "__main__":
    roundup()
